### ISSUE TITLE
Registration issue:

### ISSUE THREAD

**Issue by chgresma** [cearr1112/Inventory-Management-System#3]
# Problem
- no role column in the database table: account for registration
- role payload variable should be added to the registration kay ang confirm role mahulog nag select role as first page sa registration
- confusing ang entity nga Account - staff and supplier 
- ERD problems

# Steps to reproduce
- please ko pa accept sa privilege nga eh update nako ang registration kay kuwang ang role nga data para sa role column
- will modify the account table which contains new column ROLE which serves as disjoint rule sa ERD kay dapat unta ang account nga table kay dili weak entity. Dapat unta nag weak entity is ang Staff table og ang Supplier table.

# New scheme

## Account table
| username | firstName | middleName | lastName | password | role

The account table should be the strong entity kay ang role ma serve as composite key para sa identification of roles.

**Comment by kerrlabajo** [comment]
Oo pwede ra unta mo add ta og data field sa account as role. Pero before that refer sa login.php line 73-75 unsa ako pasabot.
Furthermore, about sa confirmRole, if na click ang staffButton => INSERT into staff VALUES (NULL, $_POST['userName'].
Para ma directly access ra ang userName instead of role since ato man i pass ang iyang userName for items and itemsRequest. Same pud sa supplier if na click ang supplierButton, sa supplier nga table ma butang ang iyang userName.

**Comment by kerrlabajo** [comment]
Ako i repeat process:
1. Account for only keeping details of the person.
2. confirmRole.php provides two options after registering details
3. If either button are pressed, insert the account's username to that specific table(staff or supplier).
4. Once successful ang insert didto, proceed sa following dashboard.

**Comment by chgresma** [comment]
> Oo pwede ra unta mo add ta og data field sa account as role. Pero before that refer sa login.php line 73-75 unsa ako pasabot. Furthermore, about sa confirmRole, if na click ang staffButton => INSERT into staff VALUES (NULL, $_POST['userName']. Para ma directly access ra ang userName instead of role since ato man i pass ang iyang userName for items and itemsRequest. Same pud sa supplier if na click ang supplierButton, sa supplier nga table ma butang ang iyang userName.

sa kani po is very confusing kay kung mag log in dili rakay username ang geh basihan po, which is password and ang role nga eh identify kay mas simple and not complicated.

**Comment by chgresma** [comment]
> 2\. onfirmRole.php provides two options after registering details

so sa kani po ako nalang eh independent akong flow ani para dili na complicated og dali ra maka sabot si ma'am unsay process sa kanang registration with selection of destination role

**Comment by kerrlabajo** [comment]
Okay if confusing jud ako nlng i update ang sql
pero if naa nay role, we will remove the tables staff and supplier

**Comment by kerrlabajo** [comment]
ari ra nako i send ang sql file para inyo ma import

**Comment by chgresma** [comment]
> Okay if confusing jud ako nlng i update ang sql pero if naa nay role, we will remove the tables staff and supplier

hello po no need to delete the staff and supplier, ako nalang eh update ang sql para makasabot ka sa dali masabtan nga entity. Staff and Supplier table must be a weak entity lang po no need to delete

**Comment by chgresma** [comment]
mo take charge lang ko ani para sa data flow po.

**Comment by kerrlabajo** [comment]
Sige go lamat

**Comment by chgresma** [comment]
I will update today po for the changes of the table: Account, Staff and Supplier

**Comment by kerrlabajo** [comment]
Address lang jud kung unsa pa lain needed i review, I really appreciate it

**Comment by chgresma** [comment]
sa kaning kuan bitaw account nga table og supplier lisod na kaayo eh usab tungod sa inyuha nga part kay complicated kaayo sa akong part ang kanang roles gud dapat unta naay composite key nga column para sa identification of user roles which is the proper and simplified mag lisod nakog change ron tungod sa inyuha nga part.

**Comment by chgresma** [comment]
# The main reference for login is the role type 
Dili ang button gamiton kay naay cases mag bug na ang payload nya magkabuang ang akoa nga part.

**Comment by kerrlabajo** [comment]
Okay mo try ko revise sa database in accdg sa imo ge mention about roles
there's a reason why dili makadali2 modify ang database tungod sa mga constraint for foreign keys sa phpmyadmin nato and wala pajud ko ka resolve ana nga part

**Comment by chgresma** [comment]
ang akong nalang solution to produce kay
mag butang kog drop down nga input to serve as action to select what type of role to login

Username _____
Password _____

*dropdown* Login as
      > Staff
      > Supplier
      
  === login button ===

**Comment by chgresma** [comment]
> Okay mo try ko revise sa database in accdg sa imo ge mention about roles there's a reason why dili makadali2 modify ang database tungod sa mga constraint for foreign keys sa phpmyadmin nato and wala pajud ko ka resolve ana nga part

makaya unta nakog revise ang database kaso lang ang uban nga naka assigned task basin nyag need nila mag update, ako sad unta eh revise ang ERD para magka correlate sila

**Comment by kerrlabajo** [comment]
> ang akong nalang solution to produce kay mag butang kog drop down nga input to serve as action to select what type of role to login
> 
> Username _____ Password _____
> 
> _dropdown_ Login as > Staff > Supplier
> 
> === login button ===

Actually, ang rason jud nga nagbutang ko sa staff og supplier table para naa tay storage for the amount of available staffs and suppliers kay dili ra isa employees or accounts.
Again I will repeat ang ako idea, username is the primary key, locating where the username was stored either staff table or supplier table is an automatic task nga ato ma implement, dili ang user tanan angmaghandle

**Comment by kerrlabajo** [comment]
> > Okay mo try ko revise sa database in accdg sa imo ge mention about roles there's a reason why dili makadali2 modify ang database tungod sa mga constraint for foreign keys sa phpmyadmin nato and wala pajud ko ka resolve ana nga part
> 
> makaya unta nakog revise ang database kaso lang ang uban nga naka assigned task basin nyag need nila mag update, ako sad unta eh revise ang ERD para magka correlate sila

no need to worry ra if need ma update then we announce sa ato groupmates

**Comment by chgresma** [comment]
> > ang akong nalang solution to produce kay mag butang kog drop down nga input to serve as action to select what type of role to login
> > Username _____ Password _____
> > _dropdown_ Login as > Staff > Supplier
> > === login button ===
> 
> Actually, ang rason jud nga nagbutang ko sa staff og supplier table para naa tay storage for the amount of available staffs and suppliers kay dili ra isa employees or accounts. Again I will repeat ang ako idea, username is the primary key, locating where the username was stored either staff table or supplier table is an automatic task nga ato ma implement, dili ang user tanan angmaghandle

we can count the acount table by roles po then pragmatically check sa PHP env configuration kung pila ang naka set nga staffs and suppliers, galing lang lisod na para sa ubang naka assigned sa task.

**Comment by kerrlabajo** [comment]
> > > ang akong nalang solution to produce kay mag butang kog drop down nga input to serve as action to select what type of role to login
> > > Username _____ Password _____
> > > _dropdown_ Login as > Staff > Supplier
> > > === login button ===
> > 
> > 
> > Actually, ang rason jud nga nagbutang ko sa staff og supplier table para naa tay storage for the amount of available staffs and suppliers kay dili ra isa employees or accounts. Again I will repeat ang ako idea, username is the primary key, locating where the username was stored either staff table or supplier table is an automatic task nga ato ma implement, dili ang user tanan angmaghandle
> 
> we can count the acount table by roles po then pragmatically check sa PHP env configuration kung pila ang naka set nga staffs and suppliers, galing lang lisod na para sa ubang naka assigned sa task.

Yep as expected, pero if ingana man gali, naa tay option
whether i keep ang staff og supplier table, or remove it completely and mag rely ta sa role datafield to identify if staff siya or supplier

**Comment by kerrlabajo** [comment]
As i have promised, mo guide ko for each files and tasks sa uban nato members, there is no need to worry

**Comment by kerrlabajo** [comment]
wait naa koy i drawing okay and ako i implement imo idea kajut lang

**Comment by chgresma** [comment]
Will ask po naka discuss ba si ma'ama atong Completeness constraint?

**Comment by kerrlabajo** [comment]
> Will ask po naka discuss ba si ma'ama atong Completeness constraint?

nope

**Comment by kerrlabajo** [comment]
![image](https://user-images.githubusercontent.com/93184975/172014943-c3512291-b85d-4d8e-9999-2e29c8f9189f.png)
is this what you mean?

**Comment by chgresma** [comment]
kana lageh Completeness constraint mao na akong geh buhat

**Comment by chgresma** [comment]
ako nalang eh remake eh revise nako tanan asta ang database para dili maka lisod ang uban

**Comment by kerrlabajo** [comment]
> kana lageh Completeness constraint mao na akong geh buhat

yes okay basically, ang atong erd ing ana na daan except walay role nga datafield. dili siya obvious man gud sa erd design and dili ko kahibaw unsaon to pagdesign or even sa phpmyadmin Designer

**Comment by kerrlabajo** [comment]
ge tuyo nako wala ge add ang role, since ganahan ko maka try mo og automatic nato mapangita unsa iyang role thru username alone
i guess lisod pa para ninyo since we discussed new sql statements that can directly access specific data fields this week
e.g. "staff.userName = $_POST['userName'] or supplier.userName =$_POST['userName'] "
if wala pa ka gets sa ako gementioned above then yes, we will go with your idea nlng

**Comment by chgresma** [comment]
diba naka add kag employee type nga attribute para sa subdiscriminator mao na akong geh mean nga mag add og column sa account og role

**Comment by chgresma** [comment]
dili na sya automatic, ang term ana is pragmatically hard coded

**Comment by chgresma** [comment]
> ge tuyo nako wala ge add ang role, since ganahan ko maka try mo og automatic nato mapangita unsa iyang role thru username alone i guess lisod pa para ninyo since we discussed new sql statements that can directly access specific data fields this week e.g. "staff.userName = $_POST['userName'] or supplier.userName =$_POST['userName'] " if wala pa ka gets sa ako gementioned above then yes, we will go with your idea nlng

dili na sya automatic, ang term ana is pragmatically hard coded

**Comment by chgresma** [comment]
kung automatic pana sya dapat unta identified by composite key which is the role dili ang table mismo kay geh hardcode nga selection of role type or sa button mahitabo like duha ka button for example log in as Supplier log in as Staff

**Comment by chgresma** [comment]
ganahan unta ko usa lang ka button nya with two inputs only then automatically ang authentication nabahala mag identify unsa nga specific page iyang ma redirect because of the role type pwede ra dili eh delete ang table nga Staff and Supplier kay naka base ang staffId og supplierId sa laing table asta ang username.

**Comment by kerrlabajo** [comment]
There is no need to justify automatic ba or not. I am showing unsa ang process para makita ang solution previously without role datafield.

**I know about LOGIN AS STAFF and LOGIN AS SUPPLIER because that is what we did previously sa oop2 I deliberately chose not to add those buttons, because i want to have our system figure itself where the username belongs to(either staff or supplier) because Facebook or messenger or youtube for example never asks what type of user you are because they only get your identifier, and look for where role you belong** That's my idea, and if against ka kay complicated, then sure we will go back to the easier route as last time.

Also, you have groupmates, you don't have to keep telling basin maglisud ang uban. you.tell.us what is ang lisud
and i will help explain

**Comment by kerrlabajo** [comment]
> ganahan unta ko usa lang ka button nya with two inputs only then automatically ang authentication nabahala mag identify unsa nga specific page iyang ma redirect because of the role type pwede ra dili eh delete ang table nga Staff and Supplier kay naka base ang staffId og supplierId sa laing table asta ang username.

I already get your point the moment ni open ka ani nga issue at the topmost no worries

**Comment by chgresma** [comment]
> because i want to have our system figure itself where the username belongs to(either staff or supplier) because Facebook or messenger or youtube for example never asks what type of user you

I know how this will work base asa akong knowledge lang so dili dapat ang table gamiton as identification mao na akong point.

**Comment by chgresma** [comment]
kay ang kanang staff og supplier man gud kay ge himong strong entity which is ang account unta dapat nya kanang duha ka table kay subtype nalang base sa role composite key sa parent entity.

**Comment by kerrlabajo** [comment]
Charmaine, you already said your point. I am not against you. I am not imposing. I am only showing a process that has better sql statement and use of new commands from recent topics to avoid using basic sql statements
I know what you meant strong entity, weak entity, parent entity, subtype entity

**Comment by chgresma** [comment]
naa rakoy geh add para sa akoa nga part para concise ra.

**Comment by chgresma** [comment]
# This problem is already solved.

### [Click to refer this object](https://github.com/cearr1112/Inventory-Management-System/commit/06d06e0cdd7beaf44a4059acf5d9219beac16b0b)

Please ko update sa **Register.php**
- dapat maka insert og role sa account table inig register
- should also insert the data password from registration as a copy to the account_old_passwords table on submitting the form register
- please ko check sa new `role` column sa account table
